[package]
name = "serde_json_tests"
version = "0.6.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
build = "build.rs"

[features]
default = ["serde_macros"]
with-syntex = ["syntex", "serde_codegen"]
nightly-testing = ["clippy", "serde_json/clippy"]

[build-dependencies]
syntex = { version = "*", optional = true }
serde_codegen = { version = "*", optional = true }

[dependencies]
clippy = { version = "^0.*", optional = true }
num = "*"
rustc-serialize = "*"
serde = "*"
serde_json = { version = "*", path = "../json" }
serde_macros = { version = "*", optional = true }

[[test]]
name = "test"
path = "tests/test.rs"

[[bench]]
name = "bench"
path = "benches/bench.rs"
