[package]
name = "serde_json_tests"
version = "0.6.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
build = "build.rs"

[features]
default = ["serde_macros"]
with-syntex = ["syntex", "serde_codegen"]

[build-dependencies]
syntex = { version = "*", optional = true }

[dependencies]
num = "*"
rustc-serialize = "*"
serde_json = { version = "*", path = "../json" }

[dependencies.serde]
git = "https://github.com/serde-rs/serde"
rev = "9ae47a261e2e2f7dacc44c91e315fc90675e4e4b"

[dependencies.serde_macros]
git = "https://github.com/serde-rs/serde"
optional = true
rev = "9ae47a261e2e2f7dacc44c91e315fc90675e4e4b"

[build-dependencies.serde_codegen]
git = "https://github.com/serde-rs/serde"
optional = true
rev = "9ae47a261e2e2f7dacc44c91e315fc90675e4e4b"

[[test]]
name = "test"
path = "tests/test.rs"

[[bench]]
name = "bench"
path = "benches/bench.rs"
