[package]
name = "serde_json_tests"
version = "0.8.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
build = "build.rs"

[features]
default = ["serde_macros"]
with-syntex = ["syntex", "serde_codegen", "indoc/with-syntex"]
unstable-testing = ["clippy", "serde_json/clippy"]

[build-dependencies]
indoc = "*"
serde_codegen = { version = "0.8.0", optional = true }
skeptic = "^0.4.0"
syntex = { version = "*", optional = true }

[dependencies]
clippy = { version = "^0.*", optional = true }
indoc = "*"
num-traits = "*"
rustc-serialize = "*"
serde = "0.8.0"
serde_json = { path = "../json" }
serde_macros = { version = "0.8.0", optional = true }
skeptic = "^0.4.0"

[[test]]
name = "test"
path = "tests/test.rs"

[[bench]]
name = "bench"
path = "benches/bench.rs"
