[package]
name = "serde_json_tests"
version = "0.8.6"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
build = "build.rs"
publish = false

[features]
default = ["serde_derive"]
with-syntex = ["syntex", "serde_codegen", "indoc/with-syntex"]
unstable-testing = ["clippy", "serde_json/clippy"]

[build-dependencies]
indoc = "*"
serde_codegen = { version = "0.9.0-rc2", optional = true }
skeptic = "0.6"
syntex = { version = "*", optional = true }

[dependencies]
clippy = { version = "^0.*", optional = true }
indoc = "*"
num-traits = "*"
rustc-serialize = "*"
serde = "0.9.0-rc2"
serde_json = { path = "../json" }
serde_derive = { version = "0.9.0-rc2", optional = true }
skeptic = "0.6"

[[test]]
name = "test"
path = "tests/test.rs"
