[package]
name = "serde_json"
version = "0.7.4"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A JSON serialization file format"
repository = "https://github.com/serde-rs/json"
documentation = "https://serde-rs.github.io/json/serde_json/"
readme = "../README.md"
keywords = ["json", "serde", "serialization"]

[features]
nightly-testing = ["clippy"]
preserve_order = ["linked-hash-map", "linked-hash-map/serde_impl"]

[dependencies]
serde = "^0.7.0"
num-traits = "~0.1.32"
clippy = { version = "^0.*", optional = true }
linked-hash-map = { version = "0.1", optional = true }
itoa = "0.1"
dtoa = "0.1"
