[package]
name = "serde_json"
version = "0.6.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A JSON serialization file format"
repository = "https://github.com/serde-rs/json"
documentation = "https://serde-rs.github.io/json/serde_json/"
readme = "../README.md"
keywords = ["json", "serde", "serialization"]

[dependencies]
serde = "*"

[dependencies.num]
version = "*"
default-features = false
